name: 'Parse Issue to PR'
description: 'Parses the isssue and creates a PR'
inputs:
  starting-parse-symbol:
    description: 'The parsing symbol that specifies the start of the parsing characters.'
    required: true
    default: '<!--::-->'
  path-to-save:
    description: 'The path of the files that needs to be saved.'
    required: true
    default: "./tweets"
  file-name-format:
    description: 'The file name format that needs to be stored as'
    required: true
    default: "dd-MM-yyyy"
  file-name-extension:
    description: "The extension that needs to be used for the tweet file."
    required: true
    default: "tweet"
runs:
  using: 'node12'
  main: 'index.js'