name: 'Parse Issue to PR'
description: 'Parses the isssue and creates a PR'
inputs:
  starting-parse-symbol:
    description: 'The parsing symbol that specifies the start of the parsing characters.'
    required: true
    default: '##??##'
runs:
  using: 'node12'
  main: 'index.js'