name: CI
on:
  issues:
    type: ['opened']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: parsing from body of the issue
        uses: ./
        id: hello
        with:
          starting-parse-symbol: '<!--::-->'