name: CI
on:
  issues:
    type: ['opened']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: parsing from body of the issue
        uses: ./
        id: hello
        with:
          starting-parse-symbol: '<!--::-->'
          file-name-extension: 'haitweets'
      - name: Git commit
        run: |
          # git commit if there's any change
          if test -n "$(git status --porcelain 2>/dev/null)"; then
              git config --global user.email "github.gkarthiks@gmail.com"
              git config --global user.name "PR Bot"
              git add .
              git commit -m "Update forks data"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}